spring:
  application:
    name: jyp-server-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/jyp-dev
    username: jypdev
    password: password
    platform: postgres
    hikari:
      auto-commit: false
      idle-timeout: 10000
      minimumIdle: 10
      maximum-pool-size: 30
      read-only: false
      connection-timeout: 20000
      data-source-properties:
        stringtype: unspecified
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

app:
  name: jyp-server
  security:
    jwt:
      expires-in:
      secret:

  thread:
    email-service-pool:
      size: 3

  jyp:
    url: http://localhost:8080
    secret:
    access-token:
    file:
      nickname-path: src/main/resources/nickname.csv

  cloud:
    aws:

  web:

  social:
    kakao:
      client-id:
      redirect:
      url: https://dapi.kakao.com

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/v1/**
    - /test/**

server:
  port: 8080
  error:
    whitelabel:
      enabled: true
